In [1]:
import torch
import numpy as np

torch.__version__

'2.3.0+cpu'

In [2]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [3]:
arr.dtype

dtype('int32')

In [4]:
type(arr)

numpy.ndarray

In [5]:
np_arr = torch.from_numpy(arr)
np_arr

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [6]:
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [7]:
arr2d = np.arange(0.0, 12.0)

In [8]:
arr2d = arr2d.reshape(4, 3)
arr2d

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [9]:
torch.from_numpy(arr2d)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [10]:
arr[0] = 99
arr

array([99,  2,  3,  4,  5])

In [11]:
# original array affects the tensor
np_arr

tensor([99,  2,  3,  4,  5], dtype=torch.int32)

In [12]:
tmp_arr = np.arange(0, 10)
tmp_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
torch_tensor = torch.tensor(tmp_arr)
torch_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [14]:
torch_np_tensor = torch.from_numpy(tmp_arr)
torch_np_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [15]:
tmp_arr[0] = 100
tmp_arr

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [16]:
# numpy tensor has been affected
torch_np_tensor

tensor([100,   1,   2,   3,   4,   5,   6,   7,   8,   9], dtype=torch.int32)

In [17]:
# pytorch tensor has not been affected
torch_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [18]:
arr2 = np.array([1, 2, 3])
arr2.dtype

dtype('int32')

In [19]:
torch.tensor(arr2)

tensor([1, 2, 3], dtype=torch.int32)

In [20]:
arr_Tensor = torch.Tensor(arr2)
# arr_Tensor = torch.FloatTensor(arr2) # exactly same as torch.Tensor()
arr_Tensor.dtype

torch.float32

In [21]:
# extremely close to zero
torch.empty(2, 2)

tensor([[0., 0.],
        [0., 0.]])

In [22]:
# actual zero
# normally torch uses float32
torch.zeros(4, 3, dtype=torch.int64)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [23]:
torch.ones(4, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [26]:
torch.arange(0, 23, 2)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [28]:
torch.arange(0, 23, 2).reshape(4, 3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16],
        [18, 20, 22]])